# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkynHuCEGFtfFkLZw4hDUfArvGWD6Y5G
"""

import os
import pandas as pd
import numpy as np
import pickle
import re
import requests
import concurrent.futures
from bs4 import BeautifulSoup
from pathlib import Path
from datetime import datetime, timedelta, timezone

# ==========================================
# 設定: Discord Webhook (GitHub Secretsから読み込み)
# ==========================================
DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL")

# 日本時間の定義 (GitHubサーバーはUTCなので必須)
JST = timezone(timedelta(hours=9), 'JST')

# ==========================================
# 1. スクレイパー (クラス定義)
# ==========================================
class BoatRaceScraperV4:
    BASE_URL = "https://www.boatrace.jp/owpc/pc/race/beforeinfo"
    LIST_URL = "https://www.boatrace.jp/owpc/pc/race/racelist"
    INDEX_URL = "https://www.boatrace.jp/owpc/pc/race/index"

    COURSE_MAP = {
        "桐生": "01", "戸田": "02", "江戸川": "03", "平和島": "04", "多摩川": "05",
        "浜名湖": "06", "蒲郡": "07", "常滑": "08", "津": "09", "三国": "10",
        "びわこ": "11", "住之江": "12", "尼崎": "13", "鳴門": "14", "丸亀": "15",
        "児島": "16", "宮島": "17", "徳山": "18", "下関": "19", "若松": "20",
        "芦屋": "21", "福岡": "22", "唐津": "23", "大村": "24"
    }

    def __init__(self):
        self.headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}

    def _get_soup(self, url, retries=2):
        for i in range(retries):
            try:
                res = requests.get(url, headers=self.headers, timeout=15)
                res.raise_for_status()
                return BeautifulSoup(res.content, "html.parser")
            except:
                continue
        return None

    def fetch_active_courses(self, date_str):
        soup = self._get_soup(f"{self.INDEX_URL}?hd={date_str}")
        if not soup: return []
        active_courses = []
        inv_map = {v: k for k, v in self.COURSE_MAP.items()}
        for link in soup.select("a[href*='jcd=']"):
            m = re.search(r"jcd=(\d{2})", link['href'])
            if m and m.group(1) in inv_map:
                active_courses.append(inv_map[m.group(1)])
        return sorted(list(set(active_courses)))

    def fetch_race_data(self, course, rno, date_str):
        jcd = self.COURSE_MAP[course]
        try:
            # 1. 出走表から基本情報と締切時刻を取得
            soup_list = self._get_soup(f"{self.LIST_URL}?rno={rno}&jcd={jcd}&hd={date_str}")
            if not soup_list: return None

            deadline_str = "00:00"
            text_full = soup_list.get_text()
            match_time = re.search(r"締切予定.*?(\d{1,2}:\d{2})", text_full)
            if match_time: deadline_str = match_time.group(1).zfill(5)

            bodies = soup_list.select("tbody.is-fs12")
            if not bodies: bodies = soup_list.select("tbody")

            row1 = None
            for b_idx, b in enumerate(bodies):
                if "１" in b.text[:10]: row1 = b; break
            if not row1: return None

            rank_1, win_rate_1 = "B2", 0.0
            rank_match = re.search(r"/ ([AB][12])", row1.text)
            if rank_match: rank_1 = rank_match.group(1)

            td_texts = [td.text.strip().replace("\n", " ") for td in row1.find_all("td")]
            all_rates = re.findall(r"(\d\.\d{2})", " ".join(td_texts))
            if all_rates: win_rate_1 = float(all_rates[0])

            # 2. 直前情報から展示データを取得
            soup_info = self._get_soup(f"{self.BASE_URL}?rno={rno}&jcd={jcd}&hd={date_str}")
            if not soup_info or "データがありません" in soup_info.text: return None

            weather = soup_info.select_one(".weather1")
            wind_speed, wave = 0, 0
            if weather:
                txt = weather.text
                w_m = re.search(r"風速.*?(\d+)m", txt)
                h_m = re.search(r"波高.*?(\d+)cm", txt)
                if w_m: wind_speed = int(w_m.group(1))
                if h_m: wave = int(h_m.group(1))

            table = soup_info.select_one(".is-w748")
            if not table: return None
            rows = table.select("tbody")
            ex_times, st_list = [], []
            for i in range(6):
                tds = rows[i].select("td")
                if len(tds) < 5 or not tds[4].text.strip(): return None
                ex_times.append(float(tds[4].text.strip()))
                st_text = tds[2].select_one(".is-fs11").text.strip() if tds[2].select_one(".is-fs11") else "0.00"
                st_list.append(float(re.search(r"(\.\d+)", st_text).group(1)) if re.search(r"(\.\d+)", st_text) else 0.0)

            ex_rank = pd.Series(ex_times).rank(method="min").tolist()

            data = {
                "wind_speed": wind_speed, "wave": wave,
                "ex_rank_1": ex_rank[0], "rank_1": rank_1, "win_rate_1": win_rate_1,
                "deadline": deadline_str
            }
            for i in range(6):
                data[f"st_{i+1}"] = st_list[i]
                data[f"ex_time_{i+1}"] = ex_times[i]
            return data
        except: return None

# ==========================================
# 2. 予測ロジック
# ==========================================
def predict_single(model, config, scraper, course, rno, date_str):
    try:
        race_data = scraper.fetch_race_data(course, rno, date_str)
        if not race_data: return None, -1 # データなし

        # モデル入力用データの作成
        rank_map = {"A1": 4, "A2": 3, "B1": 2, "B2": 1}
        rank_val_1 = rank_map.get(race_data["rank_1"], 2)
        is_debuff_1 = 1 if (rank_val_1 <= 2 and race_data["ex_rank_1"] >= 4) else 0

        input_data = race_data.copy()
        input_data["rank_val_1"] = rank_val_1
        input_data["is_debuff_1"] = is_debuff_1

        # 予測実行
        input_df = pd.DataFrame([input_data])[config["features"]]
        prob = model.predict(input_df)[0]

        # 買い目生成
        ex_times_26 = {i: race_data[f"ex_time_{i}"] for i in range(2, 7)}
        axis_boat = min(ex_times_26, key=ex_times_26.get)

        res_dict = {
            "場名": course, "レース": f"{rno}R", "締切": race_data['deadline'],
            "確率": f"{prob:.1%}", "買い目": f"{axis_boat}頭流", "rank1": race_data["rank_1"]
        }

        if prob >= config["best_threshold"]:
            return res_dict, 1 # 推奨
        return res_dict, 0 # 推奨外

    except Exception:
        return None, -2

# ==========================================
# 3. メイン実行 (安全版パトロール)
# ==========================================
def run_github_patrol():
    print("👮 Smart Patrol Starting (JST)...")
    
    # モデル読み込み
    model_path = Path("boatrace_model_v3.pkl")
    config_path = Path("model_config.pkl")
    
    if not model_path.exists():
        print("Error: Model files not found.")
        return

    with open(model_path, "rb") as f: model = pickle.load(f)
    with open(config_path, "rb") as f: config = pickle.load(f)

    scraper = BoatRaceScraperV4()
    
    # 現在時刻(JST)
    now_jst = datetime.now(JST)
    date_str = now_jst.strftime("%Y%m%d")
    
    print(f"Current Time (JST): {now_jst.strftime('%H:%M')}")

    # 開催場取得
    courses = scraper.fetch_active_courses(date_str)
    if not courses:
        print("No races today.")
        return

    print(f"Active Courses: {len(courses)} venues")
    hits = []

    # === 🛡️ ここを安全仕様に変更 ===
    # 並列処理(ThreadPool)をやめて、1つずつ順番に処理する
    # これならサーバーに負荷をかけない
    
    for c in courses:
        for r in range(1, 13):
            try:
                # 1秒休む 
                time.sleep(1) 
                
                # 予測実行
                res, status = predict_single(model, config, scraper, c, r, date_str)
                
                # 「推奨(status=1)」かつ「データ取得成功」の場合
                if status == 1 and res:
                    race_dt_str = f"{date_str} {res['締切']}"
                    race_dt = datetime.strptime(race_dt_str, "%Y%m%d %H:%M").replace(tzinfo=JST)
                    
                    diff = race_dt - now_jst
                    minutes_left = diff.total_seconds() / 60
                    
                    # 締切まで10分〜35分
                    if 10 <= minutes_left <= 35:
                        print(f"Found! {c} {r}R") # ログ確認用
                        hits.append(res)
            except Exception as e:
                # エラーが出ても止まらないようにする
                # print(f"Error at {c} {r}R: {e}") 
                pass

    # 通知処理
    if hits:
        print(f"🎯 Found {len(hits)} actionable races!")
        hits.sort(key=lambda x: x['締切'])
        
        content = "🤖 **激アツ直前通知** (締切10〜30分前)\n"
        for r in hits:
            content += f"**{r['場名']} {r['レース']}** (締切 {r['締切']})\n"
            content += f"確率: `{r['確率']}`  買い目: `{r['買い目']}`\n"
            content += "------------------------\n"
        
        if DISCORD_WEBHOOK_URL:
            requests.post(DISCORD_WEBHOOK_URL, json={"content": content})
            print("Notification sent to Discord.")
        else:
            print("Webhook URL is missing.")
    else:
        print("No races found in the target time window.")

if __name__ == "__main__":
    run_github_patrol()
